name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧪 Tests'
    labels:
      - 'test'
      - 'tests'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🔧 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
      - 'maintenance'
  - title: '⚡ Performance'
    labels:
      - 'performance'
      - 'perf'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'test'
      - 'tests'
      - 'chore'
      - 'dependencies'
      - 'maintenance'
      - 'documentation'
      - 'docs'
  default: patch
template: |
  ## Changes

  $CHANGES

  ## Contributors

  Thanks to all contributors who made this release possible! 🎉

autolabeler:
  - label: 'chore'
    files:
      - '*.md'
      - '.github/**/*'
      - '.gitignore'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/bugfix\/.+/'
    title:
      - '/fix/i'
      - '/bug/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
    title:
      - '/feature/i'
      - '/feat/i'
  - label: 'test'
    files:
      - '**/*_test.go'
      - '**/test/**/*'
    title:
      - '/test/i'
  - label: 'documentation'
    files:
      - '**/*.md'
    title:
      - '/doc/i'
      - '/documentation/i'